# Generated by Django 5.1.7 on 2025-04-30 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_initial'),
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blooddonation',
            options={'ordering': ['-donation_date']},
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='status',
            field=models.CharField(choices=[('pending', 'Onay Bekliyor'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='EmergencyBloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(max_length=3)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('fulfilled', 'Karşılandı'), ('cancelled', 'İptal Edildi')], default='active', max_length=20)),
                ('urgency_level', models.IntegerField(default=1, help_text='1: Normal, 2: Acil, 3: Çok Acil')),
                ('units_needed', models.IntegerField(default=1)),
                ('units_received', models.IntegerField(default=0)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_requests', to='hospitals.hospital')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-urgency_level'],
            },
        ),
        migrations.CreateModel(
            name='BloodDonationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Onay Bekliyor'), ('accepted', 'Kabul Edildi'), ('rejected', 'Reddedildi'), ('completed', 'Tamamlandı')], default='pending', max_length=20)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_responses', to=settings.AUTH_USER_MODEL)),
                ('emergency_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='donations.emergencybloodrequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('emergency_request', 'donor')},
            },
        ),
    ]
